### PR TITLE
Bump xdl to latest version

### LINKED ISSUE #663: Minor security issues in `react-native-scripts`
## Description

We are getting reports in our pipeline and local development machines of two minor/moderate security issues caused by the hoek library, using `npm audit` (https://nodesecurity.io/advisories/566). Below I’ve added the exact report of both issues. I see that the affected hoek library is included using a nested sub-sub-sub-dependency of Expo's `xdl`. Luckily this is solved already and this issue can be resolved here too, by updating `xdl` to the latest version.

I will make a PR with the update, so you guys only have to check for validity.

## Expected Behavior

I expect this library to not have any security issues.

## Observed Behavior

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ xdl                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ xdl > jsonwebtoken > joi > hoek                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ hoek                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ xdl                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ xdl > jsonwebtoken > joi > topo > hoek                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/566                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by byCedric**
Fixes #663

### CODE REVIEW

**Comment by brentvatne** [comment]
thanks!

**Comment by brentvatne** [comment]
It seems that there was some change to xdl that breaks starting the packager here, I had to revert the commit. I'll investigate further maybe next week. You can verify by adding react-native-scripts@1.14.1 to an app and trying to start the packager, it stays on "Starting packager"

**Comment by byCedric** [comment]
Sure, do you prefer to have this tested on an existing project or a brand new one?

**Comment by byCedric** [comment]
Ok, starting a new project using `npx create-react-native-app .` and chaning `react-native-scripts` to `1.14.1` results in this:

```
cedric at Cedrics-MacBook-Pro in ~/Projects/bycedric/expo-test                                                                                                                                                                          22:27
> NODE_ENV=development yarn start
yarn run v1.7.0
$ react-native-scripts start
10:28:00 PM: Starting packager...
***ERROR STARTING PACKAGER***
No issue with doctor-watchman-version
No issue with doctor-problem-checking-watchman-version
No issue with doctor-both-app-and-exp-json
No issue with doctor-schema-validation
No issue with doctor-validate-asset-fields
No issue with doctor-schema-validation-exception
No issue with doctor-unversioned
No issue with doctor-no-react-native-in-package-json
No issue with doctor-versions-endpoint-failed
No issue with doctor-invalid-sdk-version
No issue with doctor-node-modules-missing
No issue with doctor-react-native-not-installed
No issue with doctor-npm-not-found
No issue with doctor-could-not-run-npm-ls
No issue with doctor-problem-checking-node-modules
No issue with doctor-node-modules-issues
Scanning folders for symlinks in /Users/cedric/Projects/bycedric/expo-test/node_modules (33ms)
```

The "best part" of this is that the `ERROR STARTING PACKAGER` is caused by my node version (10) which permanently logs `(node:12531) ExperimentalWarning: The fs.promises API is experimental`. I think this is resolved when [parsing the logs of the process here](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/src/util/packager.js#L145).

When I wait for some time, my firewall is actually prompting me for node access. So I think it actually starts _something_. I also put `console.log` like everywhere in the [`xdl-src/Project.js#startAsync `](https://github.com/expo/xdl/blob/master/src/Project.js#L1656) to see where it stalled. I found out that, down the line in the [`rns-src/util/packager.js`](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/src/util/packager.js#L226), the success callback _actually gets triggered_. Which should mean that it started successfully right?

When going even further I noticed that the actual output of the packers are parsed using the output stream of with over here, [`rns-src/util/packager.js`](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/src/util/packager.js#L215). I logged this too, and found out that I _never_ receive a message with `chunk.tag === 'device'`. Instead I get tons of messages with tags from `expo` and `metro`.

**Comment by byCedric** [comment]
Well, when I was typing this I was debugging even more and found something genius. While I'm not precisely sure why no `chunk.tag === 'device'` is emitted, I found out that the hotkeys actually _do work_. So try pressing `d`, it prints the message like it thinks its working perfectly... Even when starting a simulator using `1.14.0`, closing the node server and open a `1.14.1` (with the same simulator running), _actually load the app_...

**Comment by byCedric** [comment]
So, to summarise this, I think the "first/opening message" is being blocked by the fact that the [chunk tag is not `device` anymore](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/src/util/packager.js#L214). Instead I think it's something like `metro`. The packager and the services are actually starting and working fine.

Sorry for the spam @brentvatne! Hope it helps.
❤️ the guys from @peakfijn

**Comment by brentvatne** [comment]
hey @byCedric! that does help a lot, thank you! we will go ahead and bump xdl when we release the next version of expo (in the next week or two) and make the appropriate changes for logging that you discovered

**Comment by byCedric** [comment]
We can't wait 😬

**Pull request merged**
