### PR TITLE
package.json: Build script makes executable .js

### PR DESCRIPTION
**Pull request by pdxjohnny**
Signed-off-by: John Andersen <johnandersenpdx@gmail.com>

### CODE REVIEW

**Comment by pdxjohnny** [comment]
If I run a build without this then I get the following:

```
pdxjohnny@test$ yarn start                                                                 
yarn start v1.0.2                                                                                         
$ react-native-scripts start
/bin/sh: /home/pdxjohnny/Documents/javascript/test/node_modules/.bin/react-native-scripts: Permission
 denied
error Command failed with exit code 126.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dikaiosune** [comment]
Hi! Thanks for the PR!

Is there a way to do this that will allow Windows users to contribute as well?

**Comment by anp** [comment]
Haven't heard back on this in some time, going to give it a close. If you'd like me to reopen, please reply here!

**Comment by pdxjohnny** [comment]
Thanks for closing I don't think I have bandwidth to add cross platform :-)

**Pull request closed without merging**
