### PR TITLE
Update template

### PR DESCRIPTION
**Pull request by dhruvdutt**
Update template gitignore based on [CRA](https://github.com/facebookincubator/create-react-app/blob/80a7fc391df112bcb9f2c669b3932d4b3d0856fc/packages/react-scripts/template/gitignore).

### CODE REVIEW

**Comment by dhruvdutt** [comment]
@dikaiosune @brentvatne Can you review this?

**Comment by dikaiosune** [comment]
I don't think we need a build or coverage directory ignore, we don't support `.env*` files, and I feel a bit like people should have a global gitignore with DS_Store, but the other changes look great!

**Comment by dhruvdutt** [comment]
@dikaiosune I've updated the PR as per the changes you've suggested.

**Comment by brentvatne** [comment]
thanks!

**Pull request merged**
