### PR TITLE
fixed short cd output

### PR DESCRIPTION
**Pull request by usama54321**
Fixes Issue #43

### CODE REVIEW

**Comment by dikaiosune** [comment]
Hi! Thanks for the PR!

When I initialize a new project with your changes, I run into this error:

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received false
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at ChildProcess.<anonymous> (/Users/adam/testcwd/node_modules/react-native-scripts/build/scripts/init.js:204:34)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Can you test your changes using the instructions at https://github.com/react-community/create-react-native-app/blob/master/CONTRIBUTING.md#creating-a-test-project ? Let me know if the instructions aren't clear. You may need to run `gulp clean && gulp build` in the `react-native-scripts` directory before creating the tarball.

**Comment by dikaiosune** [comment]
I think this may have been my mistake -- I attempted to init my project using my pre-existing global install of the `create-react-native-app` script. I'll take a look again soon.

**Comment by usama54321** [comment]
Hi,

I did follow all the steps in the contribution guide, tested the init.js script with the updated tarball. I have tested the issue and it is working fine

Thanks

**Comment by dikaiosune** [comment]
Yep! I see what the issue is. Any changes in the `react-native-scripts` package need to be compatible with previous versions of the `create-react-native-app` package, since we don't encourage people to update `create-react-native-app` very often.

Maybe if you reorder the argument order in the init function and provide a fallback value for `cwd` this will be backwards compatible?

**Comment by dikaiosune** [comment]
Excellent, thanks!

**Pull request merged**
