### PR TITLE
add `yarn create` command to the readme

### PR DESCRIPTION
**Pull request by gsklee**
Update installation instructions to use the new `yarn create` command

### CODE REVIEW

**Comment by brentvatne** [comment]
this isn't available yet on the latest published version of yarn as of today (yarn@0.24.5) -- it is only available in the 0.25.0 pre-release. I'll wait until that is marked as latest and in the wild for a couple of weeks before merging this. thanks!

**Comment by gsklee** [comment]
@brentvatne ? It's available [since v0.24.2](https://yarnpkg.com/blog/2017/05/12/introducing-yarn/).

**Comment by brentvatne** [comment]
ah good point! I just did a quick search in release notes and came across `Updates the yarn-create prefix` from 0.25.0 and assumed that was it. I'll try this out tomorrow

**Comment by baptistemanson** [comment]
I tested with 
```bash
$ yarn create react-native-app PR-240
```
The script ran correctly on macOS Sierra, and I was able to go up to the ios simulator without any issue.
Small nitpicking, it lists _yarnpkg start_ instead of _yarn start_

```bash
Success! Created PR-240 at /Users/matters/PR-240
Inside that directory, you can run several commands:

  yarnpkg start
    Starts the development server so you can open your app in the Expo
    app on your phone.

  yarnpkg run ios
    (Mac only, requires Xcode)
    Starts the development server and loads your app in an iOS simulator.
```

**Comment by brentvatne** [comment]
going to just follow the lead of CRA on this, they don't include in readme yet

**Pull request closed without merging**
